spring.application.name=ai-code-review-agent

server.port=8081

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging.level.root=INFO
logging.level.com.aicodereview=DEBUG