spring.application.name=ai-code-review-agent

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.chat.options.model=deepseek-coder:latest

spring.ai.ollama.embedding.options.model=nomic-embed-text